### ISSUE TITLE
"POST /auth/authorize HTTP/1.1" 500 Internal Server Error due to pydantic validation error

### ISSUE THREAD

**Issue by dky** [fuegoio/fastapi-frontend-auth-example#1]
Hello there!

Thank you for the article + sharing the source code. Immensely helpful for me to understand and get this working! 

I ran into the following exception while testing though:

```
_function
    return await dependant.call(**values)
  File "./app/api/login_api.py", line 52, in verify_authorization
    github_user = GithubUser(**user_request.json())
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for GithubUser
company
  none is not an allowed value (type=type_error.none.not_allowed)
email
  none is not an allowed value (type=type_error.none.not_allowed)
``` 

It looks like those two fields don't get sent back from Github for the user data. I ended up removing email + company from the pydantic schema.

**Comment by dky** [comment]
Update, you can get around this using the optional type.

```
from typing import Optional

email: Optional[str] = None
```

**Comment by fuegoio** [comment]
Hi! Thanks for your issue!

Yes those fields were supposed to be mandatory because I have an email and a company, but you can put them optional to validate properly Github users without those fields.
